export const cars = [
    {Brand: 'Alfa Romeo', Models: ['Guileta','159', '147','Gulia']},
    {Brand: 'Audi', Models: [ 'A1','A3', 'A6', 'A7 Sport Back', 'A8', 'Q3', 'Q5', 'Q7']},
    {Brand: 'BMW',  Models: ['Series 1', '120d', 'Series 3', '320', 'Series 5']},
    {Brand: 'Citroen',  Models: ['C1', 'C2', 'C3', 'C4', 'C5', 'DS4', 'DS5']},
    {Brand: 'Dacia',  Models: ['Logan', 'Sandero', 'Dacia']},
    {Brand: 'Fiat',  Models: ['Punto','Bravo','500L', '500X']},
    {Brand: 'Ford',  Models: ['Mondeo', 'Focus', 'Kuga', 'Capri', 'Escort']},
    {Brand: 'Honda',  Models: ['Accord', 'CRV', 'CHR']},
    {Brand: 'Hyundai', Models: ['i10', 'i30', 'Elantra', 'Tuscon']},
    {Brand: 'Mazda',  Models: ['3', '6', 'CX-5', 'CX-3', 'MX-5']},
    {Brand: 'Mercedes-Benz',  Models: ['A Klasa', 'B Klasa', 'C Klasa', 'E Klasa']},
    {Brand: 'Mitsubishi',  Models: ['Lancer', 'Outlender', 'Colt']},
    {Brand: 'Nissan',  Models: ['Qashqai']},
    {Brand: 'Opel',  Models: ['Astra', 'Insignia', 'Meriva', 'Ascona', 'Antara']},
    {Brand: 'Peugeot',  Models: ['206', '207', '208', '306', '307', '308', '508', '1008']},
    {Brand: 'Renault',  Models: ['Megane','Talisman', 'Kadjar', 'Clio', 'Twingo', 'Koleos']},
    {Brand: 'Seat',  Models: ['Ibiza', 'Leon']},
    {Brand: 'Skoda',  Models: ['Fabia', 'Octavia', 'Superb', 'Kamiq','Karoq']},
    {Brand: 'Toyota',  Models: ['RAV4', 'Corrola', 'Auris']},
    {Brand: 'VW',  Models: ['Golf', 'Passat', 'Tuareg', 'Tuaran', 'X-Roc', 'Tiguan']},
]

export const engines = [
    {Title: 'Benzin'},
    {Title: 'Dizel'},
    {Title: 'Benzin + Gas(TNG)'},
    {Title: 'Metan CNG'},
    {Title: 'Električni pogon'},
    {Title: 'Hibridni pogon'}
]

export const years = [
    {Title: '2020'},
    {Title: '2019'},
    {Title: '2018'},
    {Title: '2017'},
    {Title: '2016'},
    {Title: '2015'},
    {Title: '2014'},
    {Title: '2013'},
    {Title: '2012'},
    {Title: '2011'},
    {Title: '2010'},
    {Title: '2009'},
    {Title: '2008'},
    {Title: '2007'},
    {Title: '2006'},
    {Title: '2005'},
    {Title: '2004'},
    {Title: '2003'},
    {Title: '2002'},
    {Title: '2001'},
    {Title: '2000'},
    {Title: '1999'},
    {Title: '1998'},
    {Title: '1997'},
    {Title: '1996'},
]